### ISSUE TITLE
building throws error

### ISSUE THREAD

**Issue by mrtnpro** [rosylilly/middleman-webpack#1]
Any idea why `bundle exec middleman build` fails with the following error?

``` ruby
➜  middleman-webpack git:(master) bundle exec middleman build
/Users/martin/Development/middleman-webpack/config.rb:41:in ``': No such file or directory - npm (Errno::ENOENT)
    from /Users/martin/Development/middleman-webpack/config.rb:41:in `evaluate_configuration!'
    from /Users/martin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.0.0/lib/middleman-core/application.rb:301:in `instance_eval'
    from /Users/martin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.0.0/lib/middleman-core/application.rb:301:in `evaluate_configuration!'
    from /Users/martin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.0.0/lib/middleman-core/application.rb:277:in `start_lifecycle'
    from /Users/martin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.0.0/lib/middleman-core/application.rb:265:in `initialize'
    from /Users/martin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-cli-4.0.0/lib/middleman-cli/build.rb:51:in `new'
    from /Users/martin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-cli-4.0.0/lib/middleman-cli/build.rb:51:in `build'
    from /Users/martin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/martin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/martin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
    from /Users/martin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
    from /Users/martin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
    from /Users/martin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
    from /Users/martin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
    from /Users/martin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
    from /Users/martin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
    from /Users/martin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/martin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/martin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/martin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/martin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-cli-4.0.0/bin/middleman:23:in `<top (required)>'
    from /Users/martin/.rbenv/versions/2.3.0/bin/middleman:23:in `load'
    from /Users/martin/.rbenv/versions/2.3.0/bin/middleman:23:in `<main>'
```

**Comment by mrtnpro** [comment]
Looks like I had a messed up node/npm setup. Working now.
